# Generated by Django 2.2.2 on 2019-06-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketcher', '0003_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
