# Generated by Django 2.2.2 on 2019-06-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketcher', '0008_auto_20190625_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='sketcher/images/'),
        ),
    ]
