# Generated by Django 2.2.2 on 2019-06-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketcher', '0009_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_images'),
        ),
    ]
