# Generated by Django 2.2.2 on 2019-06-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketcher', '0011_auto_20190629_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
    ]
