# Generated by Django 2.2.2 on 2019-06-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketcher', '0012_auto_20190629_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=-1),
        ),
    ]
