# Generated by Django 2.2.2 on 2019-06-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketcher', '0013_auto_20190629_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.IntegerField(default=0),
        ),
    ]
