# Generated by Django 2.2.2 on 2019-06-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketcher', '0019_auto_20190630_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
    ]
